Add simple draft for account/role mapping
bptlab/mantichor-tezos pull request #3
Opened 2019-06-29 13:29 UTC by fyndalf

This will add support for supplying role <--> account mappings when deploying a choreography. This mapping is subsequently used for assigning accounts to roles based on the mappings, and thereby providing each role of a choreography with a different address.
A mapping is identified by its id, which is the same as the id of the associated choreography.

A choreography can for now be deployed as follows:

`POST localhost:3000/choreographies`

```json
{
	"xml": "...",
	"id": "someUniqueIdentifier",
	"mappings": [
			{
				"role": "roleA",
				"identifier": "bootstrap3"
			},
			{
				"role": "roleB",
				"identifier": "bootstrap4"
			}
		]
}
```
where `role` is the name of the role, and `identifier` is an identifier for the bootstrapped accounts that are useable with the sandboxed node.

Tasks can then be executed the following way:
`POST localhost:3000/choreographies/[id]/tasks/execute`

```json
{
	"tasks": ["taskToBeExecuted"],
	"xml": "...",
	"id": "someUniqueIdentifier",
	"role": "roleB"
}
```

where `role` is the name of the role that executes the task.
The transaction is then sent by the account associated with the role name for that choreography.

Please let me know what you think of this approach, and whether this is actually the thing we look for. As it is only a draft for now, I'm happy to make changes when required :)

2019-07-01 16:25 UTC, jan-ladleif commented
So, I took another look at the PR and think I now kind of understand the rationale. 🙂 

- The adapter has a number of accounts that we can use.
- At deploy time, we have to decide which account is mapped to which role.
- When executing a task, we have to specify a role so the associated account can be used to sign the transaction.

I have a few questions, though:
1. If two participants run individual adapters connecting to the same blockchain, how can we specify which adapter the account belongs to?
  The account identifiers seem rather local to me, not comparable to an address like in Ethereum.
2. Why do we need to specify the role when executing a task?
  It should be clear which role the task requires since we can just look at the sender (we can assume that we do not have a response message).

2019-07-02 08:38 UTC, fyndalf commented
Thanks for looking at this PR!

Regarding your questions:

1. The account identifiers do map to addresses, and we can change the supplied mapping to contain the address instead of the identifier. When running multiple adapters, we could provide each adapter with some sort of config file containing the account address and keys, and could then know what account belongs to the adapter and also know what roles the adapter "has" in each choreography based on the mappings. (although for now, all of these accounts can only be bootstrapped accounts) Would this seem feasible to you?

2. I agree that it makes more sense to extract the role from the choreography, when executing tasks. We could fall back to some default account (in the sandboxed case, at least), when no role is specified. I'll implement the behaviour in this PR.

Hope this helps, let me know what you think :grinning:

2019-07-02 09:15 UTC, jan-ladleif commented
Sounds good, both of the suggestions!

Regarding point 2: Do we need the fallback to a default account?
Using a static mapping each role should have exactly one associated account, and only that account should be able to execute tasks of that role.

Thus, wouldn't the workflow in the adapter look kinda like the following?

1. *Receive `POST localhost:3000/choreographies/[contract-address]/tasks/execute`*
1. Get the required role from the model.
1. Get the associated account from the static mapping.
1. If we own the account, use it to send the action.
1. If we do not own the account, return an error.

The last two steps would also have to be verified by the smart contract, i.e., the smart contract checks whether the origin of the transaction is the account associated to the role, and fails if it isn't.

2019-07-06 14:01 UTC, fyndalf commented
@jan-ladleif I implemented some changes with the last few commits:

- Now there is no fallback account if the mapping has no role for the account address
- Executing a task requires the address of the executing account and the mapping to be passed as well (since we don't have an ABI and need both the mapping and the XML to re-generate the contract). I've outlined it in the PR description.
- The generated smart contracts check whether the executing address actually is associated with the role, and fails if that's not the case.

What do you think, do these changes sound reasonable?

2019-07-07 14:28 UTC, jan-ladleif commented
Awesome, sounds good!

One thought: Do we really have to provide the mapping again when executing a task? If the right account is supplied, the invocation succeeds, and if not, it fails. The smart contract makes sure of that. Are there any other steps involved where we need the whole mapping?

2019-07-07 14:40 UTC, tom-lichtenstein commented
@jan-ladleif The adapter needs the role mapping to generate the correct ABI to execute the function.

2019-07-08 21:44 UTC, t-lichtenstein requested changes
The changes look good to me. As soon as the minor remarks are resolved I am happy to approve the PR.

2019-07-08 21:44 UTC, tom-lichtenstein commented on tezos-adapter/src/models/Account.ts
> +export interface AccountJSON {
The interface does not need to be exported.

2019-07-08 21:44 UTC, tom-lichtenstein commented on tezos-adapter/src/models/alphanetAccount.json
> +}
Please insert a newline :)

2019-07-08 21:44 UTC, tom-lichtenstein commented on tezos-adapter/src/translator/ContractGenerator.ts
> +    task: ChoreographyElement, joins: ChoreographyElement[], roleMappings: RoleMapping[]): string {
Maybe add a default value (roleMappings: RoleMapping[] = []) for a role mapping to prevent an exception when calling roleMappings.find()

2019-07-09 08:30 UTC, t-lichtenstein approved these changes
Looks good to me!

2019-07-09 08:35 UTC, merged